(print "Enter two numbers")
(setq a(read))
(setq b(read))

(defun gcd_num(a b)
(cond ((and (= a 0) (= b 0)) 0)
    ((or (= a 0) (= b 0)) (+ a b))
    ((= (mod a b) 0) b)
    (T (gcd_num b (mod a b))))
)

(print "Numbers :")
(terpri)
(write a)
(terpri)
(write b)
(setq gcd_val (gcd_num a b))
(print "GCD :")
(write gcd_val)
(setq lcm_val (/ (* a b) gcd_val))
(print "LCM :")
(write lcm_val)